version: '3'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-container
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/1234567890

  spring-app:
    image: backend:latest
    container_name: spring-app-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_NEO4J_URI: bolt://neo4j:7687
      SPRING_DATA_NEO4J_USERNAME: neo4j
      SPRING_DATA_NEO4J_PASSWORD: 1234567890

    depends_on:
      - neo4j
